# Generated by Django 5.2.1 on 2025-06-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
