# Generated by Django 5.2.1 on 2025-06-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=100)),
                ('email', models.CharField(verbose_name=100)),
                ('address', models.CharField(verbose_name=300)),
                ('number', models.IntegerField(verbose_name=200)),
            ],
        ),
    ]
