# Generated by Django 5.2.1 on 2025-06-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(verbose_name=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.IntegerField(verbose_name=100),
        ),
    ]
