# Generated by Django 5.2.2 on 2025-06-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_entry', models.CharField(verbose_name=100)),
                ('word_meaning', models.CharField(verbose_name=100)),
            ],
        ),
    ]
